version: '2'
services:
  db:
    container_name: pgs_1
    image: postgres:12.0-alpine

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=django_dev

    ports:
      - "192.168.1.163:5444:5432"

    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
