version: '2'
services:
  redis:
    container_name: redis_1
    image: "redis"

    environment:
     - ALLOW_EMPTY_PASSWORD=yes

    ports:
      - "192.168.1.163:6386:6379"

    volumes:
      - ./data:/data
      - ./etc/redis.conf:/usr/local/etc/redis/redis.conf
